### ISSUE TITLE
Appodeal extension is stuck at step 2

### ISSUE THREAD

**Issue by dbbinh** [appodeal/admob-configurator#12]
Hello,

I got trouble with syncing with admob. The process is stuck at step 2 as i try to enable and disable the Adsense Management API.

I have no other extension installed beside Appodeal.

Thank you

![untitled](https://cloud.githubusercontent.com/assets/20499534/16899702/e38b3a72-4c37-11e6-9088-3bee896d9546.png)

Updated: 1 error in console found: Failed to load resource: the server responded with a status of 404 () : https://www.google.com/gen204/d?zx=uf70ire9u3ku

**Comment by ralovets** [comment]
Please try to update your extension to the latest version 10.9.
