### ISSUE TITLE
Step 3 forces an admob logout

### ISSUE THREAD

**Issue by AlbertRenshaw** [appodeal/admob-configurator#16]
Why does step-3 force an admob logout, makes it feel like my password might be scraped on the admob login screen which I am forced to do with this extension running now, under the new set up.

**Comment by AlbertRenshaw** [comment]
As a good rule of thumb I like to never enter passwords while I have an extension running but this one forces me to as far as I can tell. If I disable the extension, type the password, then re-enable the extension and run step-3 again to sync my ad inventory it just logs me out again so that I must enter my password while the extension is running.

**Comment by Drengel1990** [comment]
@AlbertRenshaw Thank you for your advice. We took it into consideration. And added multi-session plugin support. Now you won`t need to enter your password if you have already logged into your account. That will allow you to easily switch between your Google accounts
