### ISSUE TITLE
Google Console Beta not working 

### ISSUE THREAD

**Issue by JoeSchr** [appodeal/admob-configurator#2]
It's not working on the oauth page.
You have to change "ctrl" to "oAuthEditorCtrl" to get the right element. Maybe there is still something else wrong. In the end I just pasted the right values from the extension into the field for origns, etc. and reroute the extension to the success url!

PS.: also would be cool, if you would let me choose with which account I want to create the appodeal console project on.

**Comment by ralovets** [comment]
The oauth page issue is fixed now.
