### ISSUE TITLE
Stuck at "Create Appodeal project"

### ISSUE THREAD

**Issue by tricki** [appodeal/admob-configurator#22]
Configuring doesn't work, I'm always stuck at "Create Appodeal project" with lots of errors in the console. It also creates a new project every time I try again. (I have actually already created a project I'd prefer to use...)

I created a new Chrome user with no other extensions. I tried logging out and in again, reinstalling the extension and deleting all appodeal projects. Nothing changed.

![image](https://user-images.githubusercontent.com/523154/29873102-6a5e3184-8d92-11e7-81cc-3642d28154b0.png)

**Comment by Drengel1990** [comment]
@tricki New version 15.10.9 has been released to fix this issue.

**Comment by tricki** [comment]
Thanks for the quick update.

The error is gone now but I get the Quota Exceeded error even though I deleted the other Appodeal projects..

Any idea if that quota is reset after some time? I see the projects only get deleted after 30 days.

**Comment by Drengel1990** [comment]
@tricki You can resume the project alone. The main thing that his name was Appodeal
http://joxi.ru/xAeKEjUY6REjmy
Then the plugin will take in to work

**Comment by Drengel1990** [comment]
@tricki  did you manage to synchronize?

**Comment by tricki** [comment]
I had to try a couple times but in the end it worked, i just had to restore one of the deleted "Appodeal" projects. Thanks for your help.

But I would prefer to be able to use appodeal without requiring an extension with such far reaching permissions (for all *.google.com sites), even if it's open source. Why not offer a guide to manually do it or explain on the site why that's not possible?

**Comment by Drengel1990** [comment]
@tricki 
Thank you for notice. We have minimized the use of permissions to
"*://*.appodeal.com/*","*://*.admob.com/*","*://console.developers.google.com/*","*://chrome.google.com/webstore/detail/appodeal/*"
