### ISSUE TITLE
Sync Stuck On 2nd Step "Enable AdMob reporting" - Appodeal Extension v15.11

### ISSUE THREAD

**Issue by chataolauj** [appodeal/admob-configurator#24]
I'm having trouble synch my Appodeal account with my AdMob account. Appodeal uses this Chrome extension to sync both accounts; current version is v15.11. I get stuck on the 2nd step, which is to "Enable reporting on AdMob"; I just get redirected to my AdMob's home dashboard. Also, my ad blocker is off when I do this step.
 
Help would be greatly appreciated!

**Comment by Drengel1990** [comment]
@chataolauj I'm need your log from google console

**Comment by Drengel1990** [comment]
@chataolauj Ctrl+Shift+I in Chrome

**Comment by devdntm** [comment]
@chataolauj try use private page in google chrome with only appodeal extension
