### ISSUE TITLE
Uncaught exception during step 4 (Cannot read property '1' of undefined)

### ISSUE THREAD

**Issue by olegcherr** [appodeal/admob-configurator#3]
I've been doing 4th step, and after a few seconds I saw an uncaught exception in the console:
`Cannot read property '1' of undefined` and it was refering to:
https://github.com/appodeal/admob-configurator/blob/master/admob.js#L510

The script was stopped then.

After a 5min of waiting I reloaded the page and clicked on 4th step again. But nothing has happend.
Then I duplicated the current tab and the process began automatically on both tabs (so weird).

After a minute it showed the message:
`Absent or wrong adunits were found for app ...`

However, a bit later it said:
`Good job! Admob is synced with Appodeal now`
I was confused ))

PS: After all, it seems like everything is syncronized properly.

**Comment by ralovets** [comment]
Already solved in the latest version
