### ISSUE TITLE
Stuck at step2

### ISSUE THREAD

**Issue by sorawit** [appodeal/admob-configurator#8]
Hi, 

I just downloaded the extension and tried using it, but it got stuck at step 2. I do not have any other extensions installed in Chrome. Help please. Thanks!

![screen shot 2016-03-24 at 7 30 50 pm](https://cloud.githubusercontent.com/assets/5730246/14034680/d038d790-f1fb-11e5-998a-12bd496627c3.png)

**Comment by ralovets** [comment]
Thank you for notifying us. New version 9.1 has been released to fix this issue.
