### ISSUE TITLE
Stuck on step 2

### ISSUE THREAD

**Issue by SolaBe** [appodeal/admob-configurator#9]
I have en error on step 2 Enabling the AdSense Management API.
![screenshot_19](https://cloud.githubusercontent.com/assets/7943419/14205239/79b25e42-f812-11e5-90a7-d183bc09c5c6.png)
![screenshot_20](https://cloud.githubusercontent.com/assets/7943419/14205240/7b61d97a-f812-11e5-908d-8bfbfadd74ba.png)

**Comment by rodrigograca31** [comment]
I just had this issued. My adblocker was causing problems.
@appodeal you guys should tell people to disable adblocking for 5 minutes while the extension works....
You already warn people when on your site....
